server:
  port: 8989
spring:
  redis:
    host: 101.200.190.58
    port: 6379
    database: 0
    password: 17851182
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.azure.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: true #\u5F00\u542F\u4E8C\u7EA7\u7F13\u5B58
logging:
  level:
    root: info
    com.azure: debug
